#!/usr/bin/env bash
# Configures Nginx with a custom 404 page
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
cat > /etc/nginx/sites-enabled/default << 'NGINX'
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;

        location / {
                try_files $uri $uri/ =404;
        }
}
NGINX
service nginx restart
